### ISSUE TITLE
Separate Libraries

### ISSUE THREAD

**Issue by jmeaster30** [jmeaster30/BlastPDF#9]
Steps that need to be done:
- [x] 1. Make the new repository
- [x] 2. Create a nuget package
- [x] 3. Make the migration in BlastPDF

I have some ideas for each of the extra libraries that I want to do but they aren't related to BlastPDF in anyway.

Also just for the ease of it we can move the BlastType stuff as well. 

BlastIMG  -> SharperImage
BlastType -> SharpTTF

For SharperImage, I want to add image processing pipelines and be able to output / convert between formats

For SharpTTF, I just feel like it can live as it's own thing. I would definitely want to be able to produce TTF files with it and possibly a GUI font designer

**Comment by jmeaster30** [comment]
BlastIMG was moved to SharperImage completely.

Working on moving BlastSharp to MyLib. Pretty close to being good

BlastTTF will live for a while longer until I can actually parse and query against the font file

**Comment by jmeaster30** [comment]
BlastSharp was moved to MyLib just BlastType left to move over!
